### ISSUE TITLE
Max sounds are not turned off when level is completed

### ISSUE THREAD

**Issue by bakerhillpins** [jessaskey/mhavocpe#205]
0.85

In the spirit of #188, if you complete a level with a Maxbot active you will continue to hear his active sound until you die.

**Comment by jessaskey** [comment]
Okay, this is one that Jerky reported via email too at some point so Im glad you entered it here because I kept forgetting about it.

**Comment by jessaskey** [comment]
I think I have addressed this now by including the max sound init into the mail pokey init routine in the gamma processor. In places where all sounds need to stop, the Alpha sends the 'kill all sounds' command... under the hood, this command simply resets all the pokey commands and registers which is what is intially called on boot. I was calling a seperate routine to reset and init all the Max sounds during boot but moved the max init into the full pokey initi routine instead. This should now mean that when the kill all sounds command is sent, that both the pokey and the max sounds should all basically get result to defaults again in one fell swoop.

**Comment by bakerhillpins** [comment]
This is not fixed in 0.86 PE.  Complete the first XX level and max sounds are still on.  If I die it's reset however.

**Comment by bakerhillpins** [comment]
0.86 PE. 
The sounds/music played when you are battling the VAXX space station (Level 21) are also not turned off if you die during the space maze.

**Comment by jessaskey** [comment]
Im not able to duplicate this on MAME for some reason... it is sorta weird. Same goes for the background sound... in MAME, it turns off every time.... if you die OR if you finish the space level and go onto the landing sequence.

**Comment by bakerhillpins** [comment]
Ok, so the quick fix you sent (ROM 9s) fixes the end of maze music never ending but I still get Max sounds after levels.

**Comment by jessaskey** [comment]
Okay, I tried something more here.... will see how it tests out. I will hit it a few times and see if I can get it to happen.

**Comment by bakerhillpins** [comment]
This is still occurring. Specifically, when completing the 1st secret level. The Maxbot sounds can clearly be heard in the background of the space maze entering level 7.  Even if you die in the maze it's still there.

There are other weird things about sound going on too. The end music after completing the 1st secret level has a pulsing to it, like the sound volume goes up and down. This pulsing is also applied to the space station explosion.

**Comment by jessaskey** [comment]
So the pulsing effect on other sounds will be solved by the Max sound going away I think… I may have to dive into this specific bug a little deeper and change the way the Max sounds are done now…. The issue at the time was that I was not able to figure out how to have an ongoing sound in the POKEY be pitch adjusted by a timer since I have never had the RPM sound driver fully documented (I only had my disassembly and my own comments to follow).

Luckily I was a able to get a copy of the RotJ source code for the RPM module which is pretty much exactly like the Havoc RPM source (Havoc was the first game to use the Gamma CPU, RotJ was the second). SOOOO. I *should* be able to do the Max sound in a much more ‘standard’ way in RPM without having these weird side effects. Story for the archives there. 😊

**Comment by jessaskey** [comment]
okay, one more attempt at fixing this one. Lets see how it goes in this testing round.

**Comment by bakerhillpins** [comment]
Still seeing this in 1.01beta.  Now Max sounds remain until you go into self test or power cycle. 

I'll try to get video of the a normal end/start of a maze and what happens at the end of the 1st secret level so you can hear what's going on with the music and explosion.

**Comment by jessaskey** [comment]
Okay, I gotta play this through get to a spot where I can trace the sequence of maze endings to track this down. Plus, I put this note above but I really need to re-architect the way that the Max sounds works now that I have the original RPM source and I understand some of the commands much better now.

**Comment by jessaskey** [comment]
So I had to spend a bunch of time to gut the whole way I was doing the Max background sound. Havoc used RPM v4.0 (Rusty's Pokey Music).... and I only had my DASM of that code along with a bunch of my own comments and interpretations. There were lots of areas of RPM that I didn't understand. Luckily @HistoricalSource had posted Crystal Castles code which used RPM v3.0 so I was able to get a few hints from that source. Recently however, @Teeray sent me a copy of RPM v5.0 from Return of the Jedi and that allowed me to understand a bit more. So.. with all of that.... I have the Max sounds now running like a normal RPM sounds and not making sounds outside of RPM and then trying to shim in code that generated sounds separately.  

Im doing more testing now.
